export type Domain = 'frontend' | 'backend' | 'data' | 'devops';

export type CatalogItem = {
  id: string;
  title: string;
  description: string;
  icon: string;
  path: string;
  domain: Domain;
  langs: string[]; // e.g., ['js', 'react', 'sql']
};

export const CATALOG: CatalogItem[] = [
  {
    id: 'tech-stack',
    title: '기술 스택 추천',
    description: '프론트/백엔드/DB/배포 조합 가이드',
    icon: '⚡',
    path: '/tech-stack',
    domain: 'devops',
    langs: ['react', 'spring', 'node', 'docker'],
  },
  {
    id: 'js-cheats',
    title: 'JS 암기장',
    description: '레벨별 JS 개념 암기와 프리뷰',
    icon: '📒',
    path: '/js-cheats',
    domain: 'frontend',
    langs: ['js'],
  },
  {
    id: 'concept-snaps',
    title: 'JS 개념 스냅샷',
    description: '표현식/문, this, async 흐름 카드',
    icon: '📚',
    path: '/concept-snaps',
    domain: 'frontend',
    langs: ['js'],
  },
  {
    id: 'async-simulator',
    title: '비동기 흐름 리허설',
    description: 'await ~ finally 시퀀스 시뮬레이션',
    icon: '🎬',
    path: '/async-simulator',
    domain: 'frontend',
    langs: ['js'],
  },
  {
    id: 'api-sandbox',
    title: 'API 실습 샌드박스',
    description: 'fetch/axios, 토큰 주입, 가짜 서버',
    icon: '🔌',
    path: '/api-sandbox',
    domain: 'backend',
    langs: ['js', 'node'],
  },
  {
    id: 'db-schema',
    title: 'DB 스키마 메이커',
    description: '요구사항 → 3NF → DDL 생성',
    icon: '🗄️',
    path: '/db-schema',
    domain: 'data',
    langs: ['sql', 'prisma'],
  },
  {
    id: 'portfolio',
    title: '포트폴리오 빌더',
    description: '프로젝트 카드/링크 구성',
    icon: '💼',
    path: '/portfolio',
    domain: 'frontend',
    langs: ['react'],
  },
  {
    id: 'interview-practice',
    title: '면접 리허설',
    description: '질문/모범답안/함정/실습',
    icon: '🎤',
    path: '/interview-practice',
    domain: 'frontend',
    langs: ['js', 'react'],
  },
  {
    id: 'missions',
    title: 'CSS 스피드런',
    description: '자동 채점으로 CSS 실습',
    icon: '⚡',
    path: '/missions',
    domain: 'frontend',
    langs: ['css'],
  },
  {
    id: 'error-doctor',
    title: '에러 닥터',
    description: '로그 진단과 복구 제안',
    icon: '🩺',
    path: '/error-doctor',
    domain: 'devops',
    langs: ['js'],
  },
  {
    id: 'commit-assistant',
    title: '커밋/PR 비서',
    description: 'Conventional Commits/PR 템플릿',
    icon: '💬',
    path: '/commit-assistant',
    domain: 'devops',
    langs: ['git'],
  },
  {
    id: 'deploy-guide',
    title: '배포 가이드',
    description: 'Vercel/Netlify/Railway/AWS 배포 튜토리얼',
    icon: '🚀',
    path: '/deploy-guide',
    domain: 'devops',
    langs: ['git', 'node', 'react'],
  },
  {
    id: 'git-simulator',
    title: 'Git 시뮬레이터',
    description: 'Git 명령어 실습 및 시각화',
    icon: '🌿',
    path: '/git-simulator',
    domain: 'devops',
    langs: ['git'],
  },
  {
    id: 'learning-paths',
    title: '러닝 경로 프리셋',
    description: '목표별 N주 로드맵',
    icon: '🗺️',
    path: '/learning-paths',
    domain: 'frontend',
    langs: ['react', 'node', 'sql'],
  },
  {
    id: 'pattern-scaffolder',
    title: '실무 패턴 주입기',
    description: 'Controller→Service→Repository',
    icon: '🏗️',
    path: '/pattern-scaffolder',
    domain: 'backend',
    langs: ['node', 'prisma'],
  },
  {
    id: 'accessibility-checker',
    title: '접근성 검사기',
    description: 'ARIA 점검 및 제안',
    icon: '♿',
    path: '/accessibility-checker',
    domain: 'frontend',
    langs: ['react'],
  },
  {
    id: 'learning-radar',
    title: '학습 레이더',
    description: '취약 개념 분석과 복습 제안',
    icon: '📡',
    path: '/learning-radar',
    domain: 'frontend',
    langs: ['js', 'react'],
  },
];

export const DOMAINS: { key: Domain; label: string }[] = [
  { key: 'frontend', label: 'Frontend' },
  { key: 'backend', label: 'Backend' },
  { key: 'data', label: 'Data' },
  { key: 'devops', label: 'DevOps' },
];

export const LANGS: { key: string; label: string; category: 'frontend' | 'backend' | 'database' | 'tool' | 'devops' }[] = [
  { key: 'html', label: 'HTML', category: 'frontend' },
  { key: 'css', label: 'CSS', category: 'frontend' },
  { key: 'js', label: 'JavaScript', category: 'frontend' },
  { key: 'ts', label: 'TypeScript', category: 'frontend' },
  { key: 'react', label: 'React', category: 'frontend' },
  { key: 'vue', label: 'Vue', category: 'frontend' },
  { key: 'node', label: 'Node.js', category: 'backend' },
  { key: 'python', label: 'Python', category: 'backend' },
  { key: 'java', label: 'Java', category: 'backend' },
  { key: 'spring', label: 'Spring Boot', category: 'backend' },
  { key: 'sql', label: 'SQL', category: 'database' },
  { key: 'prisma', label: 'Prisma', category: 'database' },
  { key: 'git', label: 'Git', category: 'devops' },
  { key: 'docker', label: 'Docker', category: 'devops' },
  { key: 'k8s', label: 'Kubernetes', category: 'devops' },
];
